/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_anneeseche (void)
{
  GtkWidget *anneeseche;
  GtkWidget *fixed1;
  GtkWidget *label21;
  GtkWidget *eventbox6;
  GtkWidget *showbutton;
  GtkWidget *eventbox7;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *eventbox4;
  GtkWidget *image1;
  GtkWidget *eventbox5;
  GtkWidget *label1;
  GtkWidget *image2;

  anneeseche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (anneeseche), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (anneeseche), fixed1);

  label21 = gtk_label_new ("");
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed1), label21, 192, 120);
  gtk_widget_set_size_request (label21, 421, 157);

  eventbox6 = gtk_event_box_new ();
  gtk_widget_show (eventbox6);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox6, 200, 32);
  gtk_widget_set_size_request (eventbox6, 312, 48);

  showbutton = gtk_button_new ();
  gtk_widget_show (showbutton);
  gtk_container_add (GTK_CONTAINER (eventbox6), showbutton);
  gtk_widget_set_size_request (showbutton, 312, 48);

  eventbox7 = gtk_event_box_new ();
  gtk_widget_show (eventbox7);
  gtk_container_add (GTK_CONTAINER (showbutton), eventbox7);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (eventbox7), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  eventbox4 = gtk_event_box_new ();
  gtk_widget_show (eventbox4);
  gtk_box_pack_start (GTK_BOX (hbox1), eventbox4, FALSE, FALSE, 0);

  image1 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_container_add (GTK_CONTAINER (eventbox4), image1);

  eventbox5 = gtk_event_box_new ();
  gtk_widget_show (eventbox5);
  gtk_box_pack_start (GTK_BOX (hbox1), eventbox5, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("\360\235\224\270\360\235\225\227\360\235\225\227\360\235\225\232\360\235\225\224\360\235\225\231\360\235\225\226\360\235\225\243 \360\235\225\235'\360\235\225\222\360\235\225\237\360\235\225\237\360\235\225\226\314\201\360\235\225\226 \360\235\225\235\360\235\225\222 \360\235\225\241\360\235\225\235\360\235\225\246\360\235\225\244 \360\235\225\244\360\235\225\226\314\201\360\235\225\224\360\235\225\231\360\235\225\226"));
  gtk_widget_show (label1);
  gtk_container_add (GTK_CONTAINER (eventbox5), label1);

  image2 = create_pixmap (anneeseche, "closeup-shot-hand-young-lady-covered-by-red-jacket-with-green-field_181624-25977.jpeg");
  gtk_widget_show (image2);
  gtk_fixed_put (GTK_FIXED (fixed1), image2, 0, 0);
  gtk_widget_set_size_request (image2, 626, 400);

  g_signal_connect ((gpointer) showbutton, "clicked",
                    G_CALLBACK (on_showbutton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (anneeseche, anneeseche, "anneeseche");
  GLADE_HOOKUP_OBJECT (anneeseche, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (anneeseche, label21, "label21");
  GLADE_HOOKUP_OBJECT (anneeseche, eventbox6, "eventbox6");
  GLADE_HOOKUP_OBJECT (anneeseche, showbutton, "showbutton");
  GLADE_HOOKUP_OBJECT (anneeseche, eventbox7, "eventbox7");
  GLADE_HOOKUP_OBJECT (anneeseche, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (anneeseche, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (anneeseche, eventbox4, "eventbox4");
  GLADE_HOOKUP_OBJECT (anneeseche, image1, "image1");
  GLADE_HOOKUP_OBJECT (anneeseche, eventbox5, "eventbox5");
  GLADE_HOOKUP_OBJECT (anneeseche, label1, "label1");
  GLADE_HOOKUP_OBJECT (anneeseche, image2, "image2");

  return anneeseche;
}

