/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowGP (void)
{
  GtkWidget *windowGP;
  GtkWidget *fixed1;
  GtkWidget *labelGP;
  GtkWidget *buttonGP;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label3;
  GtkWidget *button_supprimerp;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label5;
  GtkWidget *button_modifierp;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label6;
  GtkWidget *button__capdef1;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label39;
  GtkWidget *button_ajoutp;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label4;

  windowGP = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowGP), _("windowGP"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (windowGP), fixed1);

  labelGP = gtk_label_new (_("GESTION DES PLANTATIONS"));
  gtk_widget_show (labelGP);
  gtk_fixed_put (GTK_FIXED (fixed1), labelGP, 88, 56);
  gtk_widget_set_size_request (labelGP, 272, 22);

  buttonGP = gtk_button_new ();
  gtk_widget_show (buttonGP);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonGP, 120, 120);
  gtk_widget_set_size_request (buttonGP, 232, 48);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonGP), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-zoom-fit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("La liste des plantes"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  button_supprimerp = gtk_button_new ();
  gtk_widget_show (button_supprimerp);
  gtk_fixed_put (GTK_FIXED (fixed1), button_supprimerp, 120, 248);
  gtk_widget_set_size_request (button_supprimerp, 232, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_supprimerp), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Supprimer une plantes"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);

  button_modifierp = gtk_button_new ();
  gtk_widget_show (button_modifierp);
  gtk_fixed_put (GTK_FIXED (fixed1), button_modifierp, 120, 312);
  gtk_widget_set_size_request (button_modifierp, 232, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_modifierp), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Modifier une plante"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox5), label6, FALSE, FALSE, 0);

  button__capdef1 = gtk_button_new ();
  gtk_widget_show (button__capdef1);
  gtk_fixed_put (GTK_FIXED (fixed1), button__capdef1, 120, 376);
  gtk_widget_set_size_request (button__capdef1, 232, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button__capdef1), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-help", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Capteurs defectueux"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox15), label39, FALSE, FALSE, 0);

  button_ajoutp = gtk_button_new ();
  gtk_widget_show (button_ajoutp);
  gtk_fixed_put (GTK_FIXED (fixed1), button_ajoutp, 120, 184);
  gtk_widget_set_size_request (button_ajoutp, 232, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_ajoutp), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Ajouter une plante"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonGP, "clicked",
                    G_CALLBACK (on_buttonGP_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supprimerp, "clicked",
                    G_CALLBACK (on_button_supprimerp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifierp, "clicked",
                    G_CALLBACK (on_button_modifierp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button__capdef1, "clicked",
                    G_CALLBACK (on_button__capdef1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ajoutp, "clicked",
                    G_CALLBACK (on_button_ajoutp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowGP, windowGP, "windowGP");
  GLADE_HOOKUP_OBJECT (windowGP, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windowGP, labelGP, "labelGP");
  GLADE_HOOKUP_OBJECT (windowGP, buttonGP, "buttonGP");
  GLADE_HOOKUP_OBJECT (windowGP, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (windowGP, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (windowGP, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowGP, label3, "label3");
  GLADE_HOOKUP_OBJECT (windowGP, button_supprimerp, "button_supprimerp");
  GLADE_HOOKUP_OBJECT (windowGP, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (windowGP, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (windowGP, image4, "image4");
  GLADE_HOOKUP_OBJECT (windowGP, label5, "label5");
  GLADE_HOOKUP_OBJECT (windowGP, button_modifierp, "button_modifierp");
  GLADE_HOOKUP_OBJECT (windowGP, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (windowGP, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (windowGP, image5, "image5");
  GLADE_HOOKUP_OBJECT (windowGP, label6, "label6");
  GLADE_HOOKUP_OBJECT (windowGP, button__capdef1, "button__capdef1");
  GLADE_HOOKUP_OBJECT (windowGP, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (windowGP, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (windowGP, image15, "image15");
  GLADE_HOOKUP_OBJECT (windowGP, label39, "label39");
  GLADE_HOOKUP_OBJECT (windowGP, button_ajoutp, "button_ajoutp");
  GLADE_HOOKUP_OBJECT (windowGP, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (windowGP, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (windowGP, image3, "image3");
  GLADE_HOOKUP_OBJECT (windowGP, label4, "label4");

  return windowGP;
}

GtkWidget*
create_windowA (void)
{
  GtkWidget *windowA;
  GtkWidget *fixed2;
  GtkWidget *label9;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *label11;
  GtkWidget *label10;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkWidget *label7;
  GtkWidget *button_ajoutp2;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label17;
  GtkWidget *button_retourA;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label8;

  windowA = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowA), _("windowA"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (windowA), fixed2);

  label9 = gtk_label_new (_("Type d'une plante"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 0, 144);
  gtk_widget_set_size_request (label9, 168, 32);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1, 208, 144);
  gtk_widget_set_size_request (entry1, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2, 208, 200);
  gtk_widget_set_size_request (entry2, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed2), entry3, 208, 256);
  gtk_widget_set_size_request (entry3, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4, 208, 312);
  gtk_widget_set_size_request (entry4, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  label11 = gtk_label_new (_("Espacement  "));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 0, 256);
  gtk_widget_set_size_request (label11, 128, 32);

  label10 = gtk_label_new (_("Dur\303\251e de maturation"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 8, 200);
  gtk_widget_set_size_request (label10, 176, 38);

  label12 = gtk_label_new (_("Identifiant de la plante"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 0, 312);
  gtk_widget_set_size_request (label12, 208, 32);

  label13 = gtk_label_new (_("Date de plantation"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 0, 368);
  gtk_widget_set_size_request (label13, 176, 24);

  jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed2), jour, 200, 368);
  gtk_widget_set_size_request (jour, 60, 32);

  mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed2), mois, 264, 368);
  gtk_widget_set_size_request (mois, 60, 32);

  annee_adj = gtk_adjustment_new (2000, 0, 3000, 1, 10, 10);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed2), annee, 328, 368);
  gtk_widget_set_size_request (annee, 72, 32);

  label7 = gtk_label_new (_("AJOUTER UNE PLANTE"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 136, 56);
  gtk_widget_set_size_request (label7, 203, 40);

  button_ajoutp2 = gtk_button_new ();
  gtk_widget_show (button_ajoutp2);
  gtk_fixed_put (GTK_FIXED (fixed2), button_ajoutp2, 304, 424);
  gtk_widget_set_size_request (button_ajoutp2, 104, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_ajoutp2), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox8), label17, FALSE, FALSE, 0);

  button_retourA = gtk_button_new ();
  gtk_widget_show (button_retourA);
  gtk_fixed_put (GTK_FIXED (fixed2), button_retourA, 8, 8);
  gtk_widget_set_size_request (button_retourA, 96, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_retourA), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox6), label8, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_ajoutp2, "clicked",
                    G_CALLBACK (on_button_ajoutp2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retourA, "clicked",
                    G_CALLBACK (on_button_retourA_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowA, windowA, "windowA");
  GLADE_HOOKUP_OBJECT (windowA, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowA, label9, "label9");
  GLADE_HOOKUP_OBJECT (windowA, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (windowA, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (windowA, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (windowA, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (windowA, label11, "label11");
  GLADE_HOOKUP_OBJECT (windowA, label10, "label10");
  GLADE_HOOKUP_OBJECT (windowA, label12, "label12");
  GLADE_HOOKUP_OBJECT (windowA, label13, "label13");
  GLADE_HOOKUP_OBJECT (windowA, jour, "jour");
  GLADE_HOOKUP_OBJECT (windowA, mois, "mois");
  GLADE_HOOKUP_OBJECT (windowA, annee, "annee");
  GLADE_HOOKUP_OBJECT (windowA, label7, "label7");
  GLADE_HOOKUP_OBJECT (windowA, button_ajoutp2, "button_ajoutp2");
  GLADE_HOOKUP_OBJECT (windowA, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (windowA, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (windowA, image8, "image8");
  GLADE_HOOKUP_OBJECT (windowA, label17, "label17");
  GLADE_HOOKUP_OBJECT (windowA, button_retourA, "button_retourA");
  GLADE_HOOKUP_OBJECT (windowA, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (windowA, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (windowA, image6, "image6");
  GLADE_HOOKUP_OBJECT (windowA, label8, "label8");

  return windowA;
}

GtkWidget*
create_windowLP (void)
{
  GtkWidget *windowLP;
  GtkWidget *fixed3;
  GtkWidget *fixed4;
  GtkWidget *treeview1;
  GtkWidget *entry5;
  GtkWidget *label14;
  GtkWidget *button_chercherLP;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label20;
  GtkWidget *button_retourLP;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label37;

  windowLP = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowLP), _("windowLP"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (windowLP), fixed3);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_fixed_put (GTK_FIXED (fixed3), fixed4, 176, 128);
  gtk_widget_set_size_request (fixed4, 50, 50);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1, 144, 80);
  gtk_widget_set_size_request (treeview1, 936, 224);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed3), entry5, 144, 312);
  gtk_widget_set_size_request (entry5, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  label14 = gtk_label_new (_("Listes des plantations"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 152, 24);
  gtk_widget_set_size_request (label14, 205, 48);

  button_chercherLP = gtk_button_new ();
  gtk_widget_show (button_chercherLP);
  gtk_fixed_put (GTK_FIXED (fixed3), button_chercherLP, 320, 312);
  gtk_widget_set_size_request (button_chercherLP, 104, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_chercherLP), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("chercher"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox10), label20, FALSE, FALSE, 0);

  button_retourLP = gtk_button_new ();
  gtk_widget_show (button_retourLP);
  gtk_fixed_put (GTK_FIXED (fixed3), button_retourLP, 24, 24);
  gtk_widget_set_size_request (button_retourLP, 104, 40);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button_retourLP), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox13), label37, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_chercherLP, "clicked",
                    G_CALLBACK (on_button_chercherLP_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retourLP, "clicked",
                    G_CALLBACK (on_button_retourLP_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowLP, windowLP, "windowLP");
  GLADE_HOOKUP_OBJECT (windowLP, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (windowLP, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (windowLP, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (windowLP, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (windowLP, label14, "label14");
  GLADE_HOOKUP_OBJECT (windowLP, button_chercherLP, "button_chercherLP");
  GLADE_HOOKUP_OBJECT (windowLP, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (windowLP, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (windowLP, image10, "image10");
  GLADE_HOOKUP_OBJECT (windowLP, label20, "label20");
  GLADE_HOOKUP_OBJECT (windowLP, button_retourLP, "button_retourLP");
  GLADE_HOOKUP_OBJECT (windowLP, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (windowLP, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (windowLP, image13, "image13");
  GLADE_HOOKUP_OBJECT (windowLP, label37, "label37");

  return windowLP;
}

GtkWidget*
create_windowS (void)
{
  GtkWidget *windowS;
  GtkWidget *fixed5;
  GtkWidget *entry6;
  GtkWidget *label15;
  GtkWidget *button_supprimerp2;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label16;
  GtkWidget *button_retourS;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label38;

  windowS = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowS), _("windowS"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (windowS), fixed5);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed5), entry6, 176, 232);
  gtk_widget_set_size_request (entry6, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  label15 = gtk_label_new (_("Entrez l'identifiant"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed5), label15, 0, 232);
  gtk_widget_set_size_request (label15, 176, 30);

  button_supprimerp2 = gtk_button_new ();
  gtk_widget_show (button_supprimerp2);
  gtk_fixed_put (GTK_FIXED (fixed5), button_supprimerp2, 344, 232);
  gtk_widget_set_size_request (button_supprimerp2, 128, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_supprimerp2), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox7), label16, FALSE, FALSE, 0);

  button_retourS = gtk_button_new ();
  gtk_widget_show (button_retourS);
  gtk_fixed_put (GTK_FIXED (fixed5), button_retourS, 8, 40);
  gtk_widget_set_size_request (button_retourS, 104, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_retourS), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox14), label38, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_supprimerp2, "clicked",
                    G_CALLBACK (on_button_supprimerp2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retourS, "clicked",
                    G_CALLBACK (on_button_retourS_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowS, windowS, "windowS");
  GLADE_HOOKUP_OBJECT (windowS, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (windowS, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (windowS, label15, "label15");
  GLADE_HOOKUP_OBJECT (windowS, button_supprimerp2, "button_supprimerp2");
  GLADE_HOOKUP_OBJECT (windowS, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (windowS, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (windowS, image7, "image7");
  GLADE_HOOKUP_OBJECT (windowS, label16, "label16");
  GLADE_HOOKUP_OBJECT (windowS, button_retourS, "button_retourS");
  GLADE_HOOKUP_OBJECT (windowS, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (windowS, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (windowS, image14, "image14");
  GLADE_HOOKUP_OBJECT (windowS, label38, "label38");

  return windowS;
}

GtkWidget*
create_windowM (void)
{
  GtkWidget *windowM;
  GtkWidget *fixed6;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *entry10;
  GtkWidget *button_modiferp2;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label19;
  GtkWidget *label21;
  GtkWidget *label23;
  GtkWidget *label25;
  GtkWidget *label22;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *entry11;
  GtkWidget *label26;
  GtkWidget *label24;
  GtkWidget *label28;
  GtkWidget *button_retourM;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label36;
  GtkWidget *button_verif;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label27;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *label32;

  windowM = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowM), _("windowM"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (windowM), fixed6);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed6), entry7, 208, 136);
  gtk_widget_set_size_request (entry7, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed6), entry8, 208, 184);
  gtk_widget_set_size_request (entry8, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed6), entry9, 208, 232);
  gtk_widget_set_size_request (entry9, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed6), entry10, 208, 96);
  gtk_widget_set_size_request (entry10, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  button_modiferp2 = gtk_button_new ();
  gtk_widget_show (button_modiferp2);
  gtk_fixed_put (GTK_FIXED (fixed6), button_modiferp2, 304, 376);
  gtk_widget_set_size_request (button_modiferp2, 120, 48);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_modiferp2), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox9), label19, FALSE, FALSE, 0);

  label21 = gtk_label_new (_("Type d'une plante"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed6), label21, 16, 136);
  gtk_widget_set_size_request (label21, 160, 32);

  label23 = gtk_label_new (_("Espacement"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed6), label23, 8, 232);
  gtk_widget_set_size_request (label23, 128, 40);

  label25 = gtk_label_new (_("Date de plantation"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed6), label25, 0, 336);
  gtk_widget_set_size_request (label25, 192, 32);

  label22 = gtk_label_new (_("dur\303\251e de maturation"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed6), label22, 8, 184);
  gtk_widget_set_size_request (label22, 192, 32);

  spinbutton4_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton4, 200, 336);
  gtk_widget_set_size_request (spinbutton4, 60, 32);

  spinbutton5_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton5, 264, 336);
  gtk_widget_set_size_request (spinbutton5, 60, 32);

  spinbutton6_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton6, 336, 336);
  gtk_widget_set_size_request (spinbutton6, 60, 32);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed6), entry11, 248, 16);
  gtk_widget_set_size_request (entry11, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  label26 = gtk_label_new (_("identifiant"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed6), label26, 152, 16);
  gtk_widget_set_size_request (label26, 88, 24);

  label24 = gtk_label_new (_("Identifiant de la plante"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed6), label24, 0, 96);
  gtk_widget_set_size_request (label24, 208, 40);

  label28 = gtk_label_new ("");
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed6), label28, 168, 480);
  gtk_widget_set_size_request (label28, 336, 72);

  button_retourM = gtk_button_new ();
  gtk_widget_show (button_retourM);
  gtk_fixed_put (GTK_FIXED (fixed6), button_retourM, 16, 24);
  gtk_widget_set_size_request (button_retourM, 96, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button_retourM), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox12), label36, FALSE, FALSE, 0);

  button_verif = gtk_button_new ();
  gtk_widget_show (button_verif);
  gtk_fixed_put (GTK_FIXED (fixed6), button_verif, 408, 16);
  gtk_widget_set_size_request (button_verif, 96, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_verif), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("verifier"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox11), label27, FALSE, FALSE, 0);

  label33 = gtk_label_new ("");
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed6), label33, 200, 304);
  gtk_widget_set_size_request (label33, 61, 22);

  label34 = gtk_label_new ("");
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed6), label34, 264, 304);
  gtk_widget_set_size_request (label34, 61, 22);

  label35 = gtk_label_new ("");
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed6), label35, 336, 296);
  gtk_widget_set_size_request (label35, 61, 22);

  label29 = gtk_label_new ("");
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed6), label29, 376, 88);
  gtk_widget_set_size_request (label29, 144, 40);

  label30 = gtk_label_new ("");
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed6), label30, 376, 136);
  gtk_widget_set_size_request (label30, 144, 32);

  label31 = gtk_label_new ("");
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed6), label31, 376, 176);
  gtk_widget_set_size_request (label31, 144, 32);

  label32 = gtk_label_new ("");
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed6), label32, 376, 232);
  gtk_widget_set_size_request (label32, 136, 32);

  g_signal_connect ((gpointer) button_modiferp2, "clicked",
                    G_CALLBACK (on_button_modiferp2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retourM, "clicked",
                    G_CALLBACK (on_button_retourM_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_verif, "clicked",
                    G_CALLBACK (on_button_verif_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowM, windowM, "windowM");
  GLADE_HOOKUP_OBJECT (windowM, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (windowM, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (windowM, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (windowM, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (windowM, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (windowM, button_modiferp2, "button_modiferp2");
  GLADE_HOOKUP_OBJECT (windowM, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (windowM, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (windowM, image9, "image9");
  GLADE_HOOKUP_OBJECT (windowM, label19, "label19");
  GLADE_HOOKUP_OBJECT (windowM, label21, "label21");
  GLADE_HOOKUP_OBJECT (windowM, label23, "label23");
  GLADE_HOOKUP_OBJECT (windowM, label25, "label25");
  GLADE_HOOKUP_OBJECT (windowM, label22, "label22");
  GLADE_HOOKUP_OBJECT (windowM, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (windowM, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (windowM, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (windowM, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (windowM, label26, "label26");
  GLADE_HOOKUP_OBJECT (windowM, label24, "label24");
  GLADE_HOOKUP_OBJECT (windowM, label28, "label28");
  GLADE_HOOKUP_OBJECT (windowM, button_retourM, "button_retourM");
  GLADE_HOOKUP_OBJECT (windowM, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (windowM, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (windowM, image12, "image12");
  GLADE_HOOKUP_OBJECT (windowM, label36, "label36");
  GLADE_HOOKUP_OBJECT (windowM, button_verif, "button_verif");
  GLADE_HOOKUP_OBJECT (windowM, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (windowM, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (windowM, image11, "image11");
  GLADE_HOOKUP_OBJECT (windowM, label27, "label27");
  GLADE_HOOKUP_OBJECT (windowM, label33, "label33");
  GLADE_HOOKUP_OBJECT (windowM, label34, "label34");
  GLADE_HOOKUP_OBJECT (windowM, label35, "label35");
  GLADE_HOOKUP_OBJECT (windowM, label29, "label29");
  GLADE_HOOKUP_OBJECT (windowM, label30, "label30");
  GLADE_HOOKUP_OBJECT (windowM, label31, "label31");
  GLADE_HOOKUP_OBJECT (windowM, label32, "label32");

  return windowM;
}

GtkWidget*
create_windowcapdef (void)
{
  GtkWidget *windowcapdef;
  GtkWidget *fixed7;
  GtkWidget *label41;
  GtkWidget *button_capdef2;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label40;

  windowcapdef = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowcapdef), _("windowcapdef"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (windowcapdef), fixed7);

  label41 = gtk_label_new ("");
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed7), label41, 48, 184);
  gtk_widget_set_size_request (label41, 368, 40);

  button_capdef2 = gtk_button_new ();
  gtk_widget_show (button_capdef2);
  gtk_fixed_put (GTK_FIXED (fixed7), button_capdef2, 104, 72);
  gtk_widget_set_size_request (button_capdef2, 272, 56);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button_capdef2), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Capteurs Defectueux"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox16), label40, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_capdef2, "clicked",
                    G_CALLBACK (on_button_capdef2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowcapdef, windowcapdef, "windowcapdef");
  GLADE_HOOKUP_OBJECT (windowcapdef, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (windowcapdef, label41, "label41");
  GLADE_HOOKUP_OBJECT (windowcapdef, button_capdef2, "button_capdef2");
  GLADE_HOOKUP_OBJECT (windowcapdef, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (windowcapdef, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (windowcapdef, image16, "image16");
  GLADE_HOOKUP_OBJECT (windowcapdef, label40, "label40");

  return windowcapdef;
}

GtkWidget*
create_fontselectiondialog1 (void)
{
  GtkWidget *fontselectiondialog1;
  GtkWidget *ok_button1;
  GtkWidget *cancel_button1;
  GtkWidget *apply_button1;
  GtkWidget *font_selection1;

  fontselectiondialog1 = gtk_font_selection_dialog_new (_("Choisir la police"));
  gtk_container_set_border_width (GTK_CONTAINER (fontselectiondialog1), 5);
  gtk_window_set_type_hint (GTK_WINDOW (fontselectiondialog1), GDK_WINDOW_TYPE_HINT_DIALOG);

  ok_button1 = GTK_FONT_SELECTION_DIALOG (fontselectiondialog1)->ok_button;
  gtk_widget_show (ok_button1);
  GTK_WIDGET_SET_FLAGS (ok_button1, GTK_CAN_DEFAULT);

  cancel_button1 = GTK_FONT_SELECTION_DIALOG (fontselectiondialog1)->cancel_button;
  gtk_widget_show (cancel_button1);
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);

  apply_button1 = GTK_FONT_SELECTION_DIALOG (fontselectiondialog1)->apply_button;
  gtk_widget_show (apply_button1);
  GTK_WIDGET_SET_FLAGS (apply_button1, GTK_CAN_DEFAULT);

  font_selection1 = GTK_FONT_SELECTION_DIALOG (fontselectiondialog1)->fontsel;
  gtk_widget_show (font_selection1);
  gtk_container_set_border_width (GTK_CONTAINER (font_selection1), 5);
  gtk_font_selection_set_preview_text (GTK_FONT_SELECTION (font_selection1), _("D\303\250s No\303\253l o\303\271 un z\303\251phyr ha\303\257 me v\303\252t de gla\303\247ons w\303\274rmiens je d\303\256ne d\342\200\231exquis r\303\264tis de b\305\223uf au kir \303\240 l\342\200\231a\303\277 d\342\200\231\303\242ge m\303\273r & c\303\246tera\302\240! 0123456789."));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fontselectiondialog1, fontselectiondialog1, "fontselectiondialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (fontselectiondialog1, ok_button1, "ok_button1");
  GLADE_HOOKUP_OBJECT_NO_REF (fontselectiondialog1, cancel_button1, "cancel_button1");
  GLADE_HOOKUP_OBJECT_NO_REF (fontselectiondialog1, apply_button1, "apply_button1");
  GLADE_HOOKUP_OBJECT_NO_REF (fontselectiondialog1, font_selection1, "font_selection1");

  return fontselectiondialog1;
}

