/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_esp_ajou (void);
GtkWidget* create_esp_mod (void);
GtkWidget* create_esp_aff (void);
GtkWidget* create_esp_supp (void);
GtkWidget* create_bwcapteur (void);
