/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowGP (void);
GtkWidget* create_windowA (void);
GtkWidget* create_windowLP (void);
GtkWidget* create_windowS (void);
GtkWidget* create_windowM (void);
GtkWidget* create_windowcapdef (void);
GtkWidget* create_fontselectiondialog1 (void);
