/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Step1 (void);
GtkWidget* create_Step2 (void);
GtkWidget* create_Step3 (void);
GtkWidget* create_Step4 (void);
GtkWidget* create_Step5 (void);
GtkWidget* create_Step6 (void);
