/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Step1 (void)
{
  GtkWidget *Step1;
  GtkWidget *fixed1;
  GtkWidget *eventbox1;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *eventbox2;
  GtkWidget *label1;
  GtkWidget *eventbox4;
  GtkWidget *button2;
  GtkWidget *eventbox3;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *eventbox25;
  GtkWidget *label2;
  GtkWidget *eventbox9;
  GtkWidget *button4;
  GtkWidget *eventbox8;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *eventbox26;
  GtkWidget *label4;
  GtkWidget *eventbox10;
  GtkWidget *button3;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *eventbox6;
  GtkWidget *label3;
  GtkWidget *eventbox11;
  GtkWidget *button5;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *eventbox12;
  GtkWidget *label5;
  GtkWidget *imageStep1;

  Step1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Step1), _("Step.1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Step1), fixed1);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox1, 253, 177);
  gtk_widget_set_size_request (eventbox1, 207, 50);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (eventbox1), button1);
  gtk_widget_set_size_request (button1, 207, 50);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  eventbox2 = gtk_event_box_new ();
  gtk_widget_show (eventbox2);
  gtk_box_pack_start (GTK_BOX (hbox1), eventbox2, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("  \360\235\220\213\360\235\220\242\360\235\220\254\360\235\220\255\360\235\220\236 \360\235\220\235\360\235\220\236\360\235\220\254 \360\235\220\234\360\235\220\245\360\235\220\242\360\235\220\236\360\235\220\247\360\235\220\255\360\235\220\254"));
  gtk_widget_show (label1);
  gtk_container_add (GTK_CONTAINER (eventbox2), label1);

  eventbox4 = gtk_event_box_new ();
  gtk_widget_show (eventbox4);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox4, 253, 281);
  gtk_widget_set_size_request (eventbox4, 207, 50);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_container_add (GTK_CONTAINER (eventbox4), button2);
  gtk_widget_set_size_request (button2, 207, 50);

  eventbox3 = gtk_event_box_new ();
  gtk_widget_show (eventbox3);
  gtk_container_add (GTK_CONTAINER (button2), eventbox3);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (eventbox3), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  eventbox25 = gtk_event_box_new ();
  gtk_widget_show (eventbox25);
  gtk_box_pack_start (GTK_BOX (hbox2), eventbox25, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("  \360\235\220\200\360\235\220\243\360\235\220\250\360\235\220\256\360\235\220\255\360\235\220\236\360\235\220\253 \360\235\220\256\360\235\220\247 \360\235\220\234\360\235\220\245\360\235\220\242\360\235\220\236\360\235\220\247\360\235\220\255 "));
  gtk_widget_show (label2);
  gtk_container_add (GTK_CONTAINER (eventbox25), label2);

  eventbox9 = gtk_event_box_new ();
  gtk_widget_show (eventbox9);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox9, 253, 505);
  gtk_widget_set_size_request (eventbox9, 207, 50);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_container_add (GTK_CONTAINER (eventbox9), button4);
  gtk_widget_set_size_request (button4, 207, 50);

  eventbox8 = gtk_event_box_new ();
  gtk_widget_show (eventbox8);
  gtk_container_add (GTK_CONTAINER (button4), eventbox8);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (eventbox8), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-dialog-error", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  eventbox26 = gtk_event_box_new ();
  gtk_widget_show (eventbox26);
  gtk_box_pack_start (GTK_BOX (hbox4), eventbox26, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("  \360\235\231\216\360\235\231\252\360\235\231\245\360\235\231\245\360\235\231\247\360\235\231\236\360\235\231\242\360\235\231\232\360\235\231\247 \360\235\231\252\360\235\231\243 \360\235\231\230\360\235\231\241\360\235\231\236\360\235\231\232\360\235\231\243\360\235\231\251 "));
  gtk_widget_show (label4);
  gtk_container_add (GTK_CONTAINER (eventbox26), label4);

  eventbox10 = gtk_event_box_new ();
  gtk_widget_show (eventbox10);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox10, 253, 394);
  gtk_widget_set_size_request (eventbox10, 207, 50);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_container_add (GTK_CONTAINER (eventbox10), button3);
  gtk_widget_set_size_request (button3, 207, 50);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  eventbox6 = gtk_event_box_new ();
  gtk_widget_show (eventbox6);
  gtk_box_pack_start (GTK_BOX (hbox3), eventbox6, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("  \360\235\220\214\360\235\220\250\360\235\220\235\360\235\220\242\360\235\220\237\360\235\220\242\360\235\220\236\360\235\220\253 \360\235\220\256\360\235\220\247 \360\235\220\234\360\235\220\245\360\235\220\242\360\235\220\236\360\235\220\247\360\235\220\255"));
  gtk_widget_show (label3);
  gtk_container_add (GTK_CONTAINER (eventbox6), label3);

  eventbox11 = gtk_event_box_new ();
  gtk_widget_show (eventbox11);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox11, 560, 592);
  gtk_widget_set_size_request (eventbox11, 108, 30);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_container_add (GTK_CONTAINER (eventbox11), button5);
  gtk_widget_set_size_request (button5, 108, 30);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  eventbox12 = gtk_event_box_new ();
  gtk_widget_show (eventbox12);
  gtk_box_pack_start (GTK_BOX (hbox5), eventbox12, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_(" \360\235\232\201\360\235\232\216\360\235\232\235\360\235\232\230\360\235\232\236\360\235\232\233"));
  gtk_widget_show (label5);
  gtk_container_add (GTK_CONTAINER (eventbox12), label5);

  imageStep1 = create_pixmap (Step1, "127794022_385444766240190_4698504979503400791_n.png");
  gtk_widget_show (imageStep1);
  gtk_fixed_put (GTK_FIXED (fixed1), imageStep1, 0, 0);
  gtk_widget_set_size_request (imageStep1, 696, 701);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Step1, Step1, "Step1");
  GLADE_HOOKUP_OBJECT (Step1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Step1, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (Step1, button1, "button1");
  GLADE_HOOKUP_OBJECT (Step1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Step1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Step1, image2, "image2");
  GLADE_HOOKUP_OBJECT (Step1, eventbox2, "eventbox2");
  GLADE_HOOKUP_OBJECT (Step1, label1, "label1");
  GLADE_HOOKUP_OBJECT (Step1, eventbox4, "eventbox4");
  GLADE_HOOKUP_OBJECT (Step1, button2, "button2");
  GLADE_HOOKUP_OBJECT (Step1, eventbox3, "eventbox3");
  GLADE_HOOKUP_OBJECT (Step1, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Step1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Step1, image3, "image3");
  GLADE_HOOKUP_OBJECT (Step1, eventbox25, "eventbox25");
  GLADE_HOOKUP_OBJECT (Step1, label2, "label2");
  GLADE_HOOKUP_OBJECT (Step1, eventbox9, "eventbox9");
  GLADE_HOOKUP_OBJECT (Step1, button4, "button4");
  GLADE_HOOKUP_OBJECT (Step1, eventbox8, "eventbox8");
  GLADE_HOOKUP_OBJECT (Step1, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Step1, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Step1, image5, "image5");
  GLADE_HOOKUP_OBJECT (Step1, eventbox26, "eventbox26");
  GLADE_HOOKUP_OBJECT (Step1, label4, "label4");
  GLADE_HOOKUP_OBJECT (Step1, eventbox10, "eventbox10");
  GLADE_HOOKUP_OBJECT (Step1, button3, "button3");
  GLADE_HOOKUP_OBJECT (Step1, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Step1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Step1, image4, "image4");
  GLADE_HOOKUP_OBJECT (Step1, eventbox6, "eventbox6");
  GLADE_HOOKUP_OBJECT (Step1, label3, "label3");
  GLADE_HOOKUP_OBJECT (Step1, eventbox11, "eventbox11");
  GLADE_HOOKUP_OBJECT (Step1, button5, "button5");
  GLADE_HOOKUP_OBJECT (Step1, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Step1, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Step1, image6, "image6");
  GLADE_HOOKUP_OBJECT (Step1, eventbox12, "eventbox12");
  GLADE_HOOKUP_OBJECT (Step1, label5, "label5");
  GLADE_HOOKUP_OBJECT (Step1, imageStep1, "imageStep1");

  return Step1;
}

GtkWidget*
create_Step2 (void)
{
  GtkWidget *Step2;
  GtkWidget *fixed2;
  GtkWidget *entry7;
  GtkWidget *treeview1;
  GtkWidget *eventbox79;
  GtkWidget *button9;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image12;
  GtkWidget *eventbox78;
  GtkWidget *label19;
  GtkWidget *eventbox81;
  GtkWidget *buttonSupp;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image20;
  GtkWidget *eventbox80;
  GtkWidget *label33;
  GtkWidget *eventbox82;
  GtkWidget *label18;
  GtkWidget *eventbox85;
  GtkWidget *button6;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image8;
  GtkWidget *eventbox84;
  GtkWidget *label9;
  GtkWidget *label50;
  GtkWidget *image7;

  Step2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Step2, 669, 550);
  gtk_window_set_title (GTK_WINDOW (Step2), _("Step.2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Step2), fixed2);
  gtk_widget_set_size_request (fixed2, 140, 31);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed2), entry7, 328, 141);
  gtk_widget_set_size_request (entry7, 195, 28);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1, 0, 224);
  gtk_widget_set_size_request (treeview1, 696, 208);

  eventbox79 = gtk_event_box_new ();
  gtk_widget_show (eventbox79);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox79, 394, 176);
  gtk_widget_set_size_request (eventbox79, 126, 26);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_container_add (GTK_CONTAINER (eventbox79), button9);
  gtk_widget_set_size_request (button9, 126, 26);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button9), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image12 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox9), image12, FALSE, FALSE, 0);

  eventbox78 = gtk_event_box_new ();
  gtk_widget_show (eventbox78);
  gtk_box_pack_start (GTK_BOX (hbox9), eventbox78, FALSE, FALSE, 1);

  label19 = gtk_label_new_with_mnemonic (_("\360\235\227\226\360\235\227\233\360\235\227\230\360\235\227\245\360\235\227\226\360\235\227\233\360\235\227\230\360\235\227\245 "));
  gtk_widget_show (label19);
  gtk_container_add (GTK_CONTAINER (eventbox78), label19);
  gtk_widget_set_size_request (label19, 96, -1);

  eventbox81 = gtk_event_box_new ();
  gtk_widget_show (eventbox81);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox81, 311, 458);
  gtk_widget_set_size_request (eventbox81, 126, 28);

  buttonSupp = gtk_button_new ();
  gtk_widget_show (buttonSupp);
  gtk_container_add (GTK_CONTAINER (eventbox81), buttonSupp);
  gtk_widget_set_size_request (buttonSupp, 126, 28);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (buttonSupp), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image20 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox15), image20, FALSE, FALSE, 0);

  eventbox80 = gtk_event_box_new ();
  gtk_widget_show (eventbox80);
  gtk_box_pack_start (GTK_BOX (hbox15), eventbox80, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("\360\235\220\222\360\235\220\224\360\235\220\217\360\235\220\217\360\235\220\221\360\235\220\210\360\235\220\214\360\235\220\204\360\235\220\221"));
  gtk_widget_show (label33);
  gtk_container_add (GTK_CONTAINER (eventbox80), label33);

  eventbox82 = gtk_event_box_new ();
  gtk_widget_show (eventbox82);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox82, 296, 112);
  gtk_widget_set_size_request (eventbox82, 251, 23);

  label18 = gtk_label_new (_("\360\235\221\275\360\235\222\206\360\235\222\226\360\235\222\212\360\235\222\215\360\235\222\215\360\235\222\206\360\235\222\233 \360\235\222\206\360\235\222\217\360\235\222\225\360\235\222\223\360\235\222\206\360\235\222\223 \360\235\222\215'\360\235\222\212\360\235\222\205\360\235\222\206\360\235\222\217\360\235\222\225\360\235\222\212\360\235\222\207\360\235\222\212\360\235\222\202\360\235\222\217\360\235\222\225 \360\235\222\205\360\235\222\226 \360\235\222\204\360\235\222\215\360\235\222\212\360\235\222\206\360\235\222\217\360\235\222\225!"));
  gtk_widget_show (label18);
  gtk_container_add (GTK_CONTAINER (eventbox82), label18);
  gtk_widget_set_size_request (label18, 251, 23);

  eventbox85 = gtk_event_box_new ();
  gtk_widget_show (eventbox85);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox85, 311, 493);
  gtk_widget_set_size_request (eventbox85, 126, 28);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_container_add (GTK_CONTAINER (eventbox85), button6);
  gtk_widget_set_size_request (button6, 126, 28);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button6), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image8 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox6), image8, FALSE, FALSE, 0);

  eventbox84 = gtk_event_box_new ();
  gtk_widget_show (eventbox84);
  gtk_box_pack_start (GTK_BOX (hbox6), eventbox84, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("\360\235\220\200\360\235\220\215\360\235\220\215\360\235\220\224\360\235\220\213\360\235\220\204\360\235\220\221"));
  gtk_widget_show (label9);
  gtk_container_add (GTK_CONTAINER (eventbox84), label9);
  gtk_widget_set_size_request (label9, 96, 17);

  label50 = gtk_label_new ("");
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed2), label50, 80, 176);
  gtk_widget_set_size_request (label50, 224, 32);

  image7 = create_pixmap (Step2, "127578339_799268073984350_1308316655641718806_n.png");
  gtk_widget_show (image7);
  gtk_fixed_put (GTK_FIXED (fixed2), image7, -8, 0);
  gtk_widget_set_size_request (image7, 784, 600);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSupp, "clicked",
                    G_CALLBACK (on_buttonSupp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Step2, Step2, "Step2");
  GLADE_HOOKUP_OBJECT (Step2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Step2, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (Step2, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Step2, eventbox79, "eventbox79");
  GLADE_HOOKUP_OBJECT (Step2, button9, "button9");
  GLADE_HOOKUP_OBJECT (Step2, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Step2, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Step2, image12, "image12");
  GLADE_HOOKUP_OBJECT (Step2, eventbox78, "eventbox78");
  GLADE_HOOKUP_OBJECT (Step2, label19, "label19");
  GLADE_HOOKUP_OBJECT (Step2, eventbox81, "eventbox81");
  GLADE_HOOKUP_OBJECT (Step2, buttonSupp, "buttonSupp");
  GLADE_HOOKUP_OBJECT (Step2, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Step2, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Step2, image20, "image20");
  GLADE_HOOKUP_OBJECT (Step2, eventbox80, "eventbox80");
  GLADE_HOOKUP_OBJECT (Step2, label33, "label33");
  GLADE_HOOKUP_OBJECT (Step2, eventbox82, "eventbox82");
  GLADE_HOOKUP_OBJECT (Step2, label18, "label18");
  GLADE_HOOKUP_OBJECT (Step2, eventbox85, "eventbox85");
  GLADE_HOOKUP_OBJECT (Step2, button6, "button6");
  GLADE_HOOKUP_OBJECT (Step2, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Step2, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Step2, image8, "image8");
  GLADE_HOOKUP_OBJECT (Step2, eventbox84, "eventbox84");
  GLADE_HOOKUP_OBJECT (Step2, label9, "label9");
  GLADE_HOOKUP_OBJECT (Step2, label50, "label50");
  GLADE_HOOKUP_OBJECT (Step2, image7, "image7");

  return Step2;
}

GtkWidget*
create_Step3 (void)
{
  GtkWidget *Step3;
  GtkWidget *fixed3;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *eventbox27;
  GtkWidget *label15;
  GtkWidget *eventbox31;
  GtkWidget *label13;
  GtkWidget *eventbox32;
  GtkWidget *label14;
  GtkWidget *eventbox33;
  GtkWidget *label11;
  GtkWidget *eventbox34;
  GtkWidget *label12;
  GtkWidget *eventbox38;
  GtkWidget *button7;
  GtkWidget *eventbox61;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image10;
  GtkWidget *eventbox36;
  GtkWidget *label16;
  GtkWidget *eventbox67;
  GtkWidget *buttonRetour;
  GtkWidget *eventbox65;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *eventbox66;
  GtkWidget *image11;
  GtkWidget *eventbox40;
  GtkWidget *label17;
  GtkWidget *eventbox71;
  GtkWidget *labelNom;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *storyA;
  GtkWidget *image9;
  GtkWidget *label52;

  Step3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Step3), _("Step.3"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Step3), fixed3);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1, 280, 88);
  gtk_widget_set_size_request (entry1, 160, 28);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry2, 280, 128);
  gtk_widget_set_size_request (entry2, 160, 28);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3, 280, 168);
  gtk_widget_set_size_request (entry3, 160, 28);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed3), entry4, 280, 208);
  gtk_widget_set_size_request (entry4, 160, 28);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed3), entry5, 280, 248);
  gtk_widget_set_size_request (entry5, 160, 28);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  eventbox27 = gtk_event_box_new ();
  gtk_widget_show (eventbox27);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox27, 97, 291);
  gtk_widget_set_size_request (eventbox27, 162, 23);

  label15 = gtk_label_new (_("\360\235\227\227\360\235\227\256\360\235\230\201\360\235\227\262 \360\235\227\261\360\235\227\262 \360\235\227\273\360\235\227\256\360\235\227\266\360\235\230\200\360\235\230\200\360\235\227\256\360\235\227\273\360\235\227\260\360\235\227\262"));
  gtk_widget_show (label15);
  gtk_container_add (GTK_CONTAINER (eventbox27), label15);
  gtk_widget_set_size_request (label15, 162, 23);

  eventbox31 = gtk_event_box_new ();
  gtk_widget_show (eventbox31);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox31, 96, 248);
  gtk_widget_set_size_request (eventbox31, 162, 23);

  label13 = gtk_label_new (_("\360\235\227\240\360\235\227\274\360\235\230\201 \360\235\227\261\360\235\227\262 \360\235\227\275\360\235\227\256\360\235\230\200\360\235\230\200\360\235\227\262"));
  gtk_widget_show (label13);
  gtk_container_add (GTK_CONTAINER (eventbox31), label13);
  gtk_widget_set_size_request (label13, 162, 23);

  eventbox32 = gtk_event_box_new ();
  gtk_widget_show (eventbox32);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox32, 96, 208);
  gtk_widget_set_size_request (eventbox32, 162, 23);

  label14 = gtk_label_new (_("\360\235\227\234\360\235\227\261\360\235\227\262\360\235\227\273\360\235\230\201\360\235\227\266\360\235\227\263\360\235\227\266\360\235\227\256\360\235\227\273\360\235\230\201"));
  gtk_widget_show (label14);
  gtk_container_add (GTK_CONTAINER (eventbox32), label14);
  gtk_widget_set_size_request (label14, 162, 23);

  eventbox33 = gtk_event_box_new ();
  gtk_widget_show (eventbox33);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox33, 97, 130);
  gtk_widget_set_size_request (eventbox33, 162, 23);

  label11 = gtk_label_new (_("  \360\235\227\243\360\235\227\277\360\235\227\262\314\201\360\235\227\273\360\235\227\274\360\235\227\272 "));
  gtk_widget_show (label11);
  gtk_container_add (GTK_CONTAINER (eventbox33), label11);
  gtk_widget_set_size_request (label11, 162, 23);

  eventbox34 = gtk_event_box_new ();
  gtk_widget_show (eventbox34);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox34, 96, 170);
  gtk_widget_set_size_request (eventbox34, 162, 23);

  label12 = gtk_label_new (_(" \360\235\227\230-\360\235\227\272\360\235\227\256\360\235\227\266\360\235\227\271 "));
  gtk_widget_show (label12);
  gtk_container_add (GTK_CONTAINER (eventbox34), label12);
  gtk_widget_set_size_request (label12, 162, 23);

  eventbox38 = gtk_event_box_new ();
  gtk_widget_show (eventbox38);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox38, 294, 328);
  gtk_widget_set_size_request (eventbox38, 122, 30);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_container_add (GTK_CONTAINER (eventbox38), button7);
  gtk_widget_set_size_request (button7, 122, 30);

  eventbox61 = gtk_event_box_new ();
  gtk_widget_show (eventbox61);
  gtk_container_add (GTK_CONTAINER (button7), eventbox61);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (eventbox61), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox7), image10, FALSE, FALSE, 0);

  eventbox36 = gtk_event_box_new ();
  gtk_widget_show (eventbox36);
  gtk_box_pack_start (GTK_BOX (hbox7), eventbox36, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_(" \360\235\232\205\360\235\232\212\360\235\232\225\360\235\232\222\360\235\232\215\360\235\232\216\360\235\232\233 "));
  gtk_widget_show (label16);
  gtk_container_add (GTK_CONTAINER (eventbox36), label16);

  eventbox67 = gtk_event_box_new ();
  gtk_widget_show (eventbox67);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox67, 528, 376);
  gtk_widget_set_size_request (eventbox67, 86, 27);

  buttonRetour = gtk_button_new ();
  gtk_widget_show (buttonRetour);
  gtk_container_add (GTK_CONTAINER (eventbox67), buttonRetour);
  gtk_widget_set_size_request (buttonRetour, 86, 27);

  eventbox65 = gtk_event_box_new ();
  gtk_widget_show (eventbox65);
  gtk_container_add (GTK_CONTAINER (buttonRetour), eventbox65);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (eventbox65), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  eventbox66 = gtk_event_box_new ();
  gtk_widget_show (eventbox66);
  gtk_box_pack_start (GTK_BOX (hbox8), eventbox66, FALSE, FALSE, 0);

  image11 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_container_add (GTK_CONTAINER (eventbox66), image11);

  eventbox40 = gtk_event_box_new ();
  gtk_widget_show (eventbox40);
  gtk_box_pack_start (GTK_BOX (hbox8), eventbox40, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_(" \360\235\221\205\360\235\221\222\360\235\221\241\360\235\221\234\360\235\221\242\360\235\221\237"));
  gtk_widget_show (label17);
  gtk_container_add (GTK_CONTAINER (eventbox40), label17);

  eventbox71 = gtk_event_box_new ();
  gtk_widget_show (eventbox71);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox71, 96, 90);
  gtk_widget_set_size_request (eventbox71, 162, 23);

  labelNom = gtk_label_new (_("\360\235\227\241\360\235\227\274\360\235\227\272 "));
  gtk_widget_show (labelNom);
  gtk_container_add (GTK_CONTAINER (eventbox71), labelNom);
  gtk_widget_set_size_request (labelNom, 162, 23);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton1, 281, 291);
  gtk_widget_set_size_request (spinbutton1, 42, 25);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton2, 328, 292);
  gtk_widget_set_size_request (spinbutton2, 42, 25);

  spinbutton3_adj = gtk_adjustment_new (2020, 1900, 3000, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton3, 377, 294);
  gtk_widget_set_size_request (spinbutton3, 63, 25);

  storyA = gtk_label_new ("");
  gtk_widget_show (storyA);
  gtk_fixed_put (GTK_FIXED (fixed3), storyA, 376, 56);
  gtk_widget_set_size_request (storyA, 232, 24);

  image9 = create_pixmap (Step3, "127531002_836787750429254_7264647349051932991_n.png");
  gtk_widget_show (image9);
  gtk_fixed_put (GTK_FIXED (fixed3), image9, 0, 0);
  gtk_widget_set_size_request (image9, 624, 416);

  label52 = gtk_label_new (_("Identifiant existe !"));
  gtk_fixed_put (GTK_FIXED (fixed3), label52, 176, 376);
  gtk_widget_set_size_request (label52, 289, 33);

  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRetour, "clicked",
                    G_CALLBACK (on_buttonRetour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Step3, Step3, "Step3");
  GLADE_HOOKUP_OBJECT (Step3, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Step3, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (Step3, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (Step3, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (Step3, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (Step3, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (Step3, eventbox27, "eventbox27");
  GLADE_HOOKUP_OBJECT (Step3, label15, "label15");
  GLADE_HOOKUP_OBJECT (Step3, eventbox31, "eventbox31");
  GLADE_HOOKUP_OBJECT (Step3, label13, "label13");
  GLADE_HOOKUP_OBJECT (Step3, eventbox32, "eventbox32");
  GLADE_HOOKUP_OBJECT (Step3, label14, "label14");
  GLADE_HOOKUP_OBJECT (Step3, eventbox33, "eventbox33");
  GLADE_HOOKUP_OBJECT (Step3, label11, "label11");
  GLADE_HOOKUP_OBJECT (Step3, eventbox34, "eventbox34");
  GLADE_HOOKUP_OBJECT (Step3, label12, "label12");
  GLADE_HOOKUP_OBJECT (Step3, eventbox38, "eventbox38");
  GLADE_HOOKUP_OBJECT (Step3, button7, "button7");
  GLADE_HOOKUP_OBJECT (Step3, eventbox61, "eventbox61");
  GLADE_HOOKUP_OBJECT (Step3, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Step3, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Step3, image10, "image10");
  GLADE_HOOKUP_OBJECT (Step3, eventbox36, "eventbox36");
  GLADE_HOOKUP_OBJECT (Step3, label16, "label16");
  GLADE_HOOKUP_OBJECT (Step3, eventbox67, "eventbox67");
  GLADE_HOOKUP_OBJECT (Step3, buttonRetour, "buttonRetour");
  GLADE_HOOKUP_OBJECT (Step3, eventbox65, "eventbox65");
  GLADE_HOOKUP_OBJECT (Step3, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Step3, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Step3, eventbox66, "eventbox66");
  GLADE_HOOKUP_OBJECT (Step3, image11, "image11");
  GLADE_HOOKUP_OBJECT (Step3, eventbox40, "eventbox40");
  GLADE_HOOKUP_OBJECT (Step3, label17, "label17");
  GLADE_HOOKUP_OBJECT (Step3, eventbox71, "eventbox71");
  GLADE_HOOKUP_OBJECT (Step3, labelNom, "labelNom");
  GLADE_HOOKUP_OBJECT (Step3, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (Step3, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (Step3, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (Step3, storyA, "storyA");
  GLADE_HOOKUP_OBJECT (Step3, image9, "image9");
  GLADE_HOOKUP_OBJECT (Step3, label52, "label52");

  return Step3;
}

GtkWidget*
create_Step4 (void)
{
  GtkWidget *Step4;
  GtkWidget *fixed4;
  GtkWidget *entry8;
  GtkWidget *entry_nom;
  GtkWidget *entryprenom;
  GtkWidget *entry12;
  GtkWidget *entry13;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *eventbox86;
  GtkWidget *label20;
  GtkWidget *eventbox89;
  GtkWidget *label35;
  GtkWidget *eventbox90;
  GtkWidget *label27;
  GtkWidget *eventbox91;
  GtkWidget *label28;
  GtkWidget *eventbox93;
  GtkWidget *label30;
  GtkWidget *eventbox94;
  GtkWidget *label29;
  GtkWidget *eventbox95;
  GtkWidget *label31;
  GtkWidget *entry14;
  GtkWidget *label49;
  GtkWidget *button14;
  GtkWidget *eventbox69;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image19;
  GtkWidget *eventbox99;
  GtkWidget *label26;
  GtkWidget *button11;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *eventbox51;
  GtkWidget *image15;
  GtkWidget *label22;
  GtkWidget *label56;
  GtkWidget *label57;
  GtkWidget *label58;
  GtkWidget *label59;
  GtkWidget *label60;
  GtkWidget *label61;
  GtkWidget *label55;
  GtkWidget *label53;
  GtkWidget *verifier;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image26;
  GtkWidget *label54;

  Step4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Step4), _("Step.4"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Step4), fixed4);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed4), entry8, 256, 23);
  gtk_widget_set_size_request (entry8, 232, 29);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry_nom = gtk_entry_new ();
  gtk_widget_show (entry_nom);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_nom, 200, 144);
  gtk_widget_set_size_request (entry_nom, 162, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom), 8226);

  entryprenom = gtk_entry_new ();
  gtk_widget_show (entryprenom);
  gtk_fixed_put (GTK_FIXED (fixed4), entryprenom, 200, 192);
  gtk_widget_set_size_request (entryprenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenom), 8226);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed4), entry12, 200, 248);
  gtk_widget_set_size_request (entry12, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed4), entry13, 208, 296);
  gtk_widget_set_size_request (entry13, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  spinbutton4_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton4, 202, 344);
  gtk_widget_set_size_request (spinbutton4, 43, 27);

  spinbutton5_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton5, 272, 344);
  gtk_widget_set_size_request (spinbutton5, 45, 25);

  spinbutton6_adj = gtk_adjustment_new (2020, 1900, 3000, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton6, 352, 344);
  gtk_widget_set_size_request (spinbutton6, 65, 25);

  eventbox86 = gtk_event_box_new ();
  gtk_widget_show (eventbox86);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox86, 32, 24);
  gtk_widget_set_size_request (eventbox86, 206, 27);

  label20 = gtk_label_new (_("\360\235\220\225\360\235\220\236\360\235\220\256\360\235\220\242\360\235\220\245\360\235\220\245\360\235\220\236\360\235\220\263 \360\235\220\236\360\235\220\247\360\235\220\255\360\235\220\253\360\235\220\236\360\235\220\253 \360\235\220\245'\360\235\220\242\360\235\220\235\360\235\220\236\360\235\220\247\360\235\220\255\360\235\220\242\360\235\220\237\360\235\220\242\360\235\220\232\360\235\220\247\360\235\220\255  "));
  gtk_widget_show (label20);
  gtk_container_add (GTK_CONTAINER (eventbox86), label20);
  gtk_widget_set_size_request (label20, 206, 27);

  eventbox89 = gtk_event_box_new ();
  gtk_widget_show (eventbox89);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox89, 24, 104);
  gtk_widget_set_size_request (eventbox89, 160, 24);

  label35 = gtk_label_new (_("\360\235\221\260\360\235\222\205\360\235\222\206\360\235\222\217\360\235\222\225\360\235\222\212\360\235\222\207\360\235\222\212\360\235\222\202\360\235\222\217\360\235\222\225 "));
  gtk_widget_show (label35);
  gtk_container_add (GTK_CONTAINER (eventbox89), label35);
  gtk_widget_set_size_request (label35, 160, 24);

  eventbox90 = gtk_event_box_new ();
  gtk_widget_show (eventbox90);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox90, 24, 144);
  gtk_widget_set_size_request (eventbox90, 160, 24);

  label27 = gtk_label_new (_("\360\235\220\215\360\235\220\250\360\235\220\246"));
  gtk_widget_show (label27);
  gtk_container_add (GTK_CONTAINER (eventbox90), label27);
  gtk_widget_set_size_request (label27, 160, 24);

  eventbox91 = gtk_event_box_new ();
  gtk_widget_show (eventbox91);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox91, 24, 192);
  gtk_widget_set_size_request (eventbox91, 160, 24);

  label28 = gtk_label_new (_("\360\235\220\217\360\235\220\253\360\235\220\236\360\235\220\247\360\235\220\250\360\235\220\246"));
  gtk_widget_show (label28);
  gtk_container_add (GTK_CONTAINER (eventbox91), label28);
  gtk_widget_set_size_request (label28, 160, 24);

  eventbox93 = gtk_event_box_new ();
  gtk_widget_show (eventbox93);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox93, 24, 296);
  gtk_widget_set_size_request (eventbox93, 160, 24);

  label30 = gtk_label_new (_("\360\235\220\214\360\235\220\250\360\235\220\255 \360\235\220\235\360\235\220\236 \360\235\220\251\360\235\220\232\360\235\220\254\360\235\220\254\360\235\220\236 "));
  gtk_widget_show (label30);
  gtk_container_add (GTK_CONTAINER (eventbox93), label30);
  gtk_widget_set_size_request (label30, 160, 24);

  eventbox94 = gtk_event_box_new ();
  gtk_widget_show (eventbox94);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox94, 24, 248);
  gtk_widget_set_size_request (eventbox94, 160, 24);

  label29 = gtk_label_new (_("\360\235\220\204-\360\235\220\246\360\235\220\232\360\235\220\242\360\235\220\245"));
  gtk_widget_show (label29);
  gtk_container_add (GTK_CONTAINER (eventbox94), label29);
  gtk_widget_set_size_request (label29, 160, 24);

  eventbox95 = gtk_event_box_new ();
  gtk_widget_show (eventbox95);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox95, 24, 344);
  gtk_widget_set_size_request (eventbox95, 160, 24);

  label31 = gtk_label_new (_("Date de naissance "));
  gtk_widget_show (label31);
  gtk_container_add (GTK_CONTAINER (eventbox95), label31);
  gtk_widget_set_size_request (label31, 160, 24);

  entry14 = gtk_entry_new ();
  gtk_widget_show (entry14);
  gtk_fixed_put (GTK_FIXED (fixed4), entry14, 200, 104);
  gtk_widget_set_size_request (entry14, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 8226);

  label49 = gtk_label_new ("");
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed4), label49, 144, 472);
  gtk_widget_set_size_request (label49, 280, 25);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed4), button14, 232, 440);
  gtk_widget_set_size_request (button14, 113, 27);

  eventbox69 = gtk_event_box_new ();
  gtk_widget_show (eventbox69);
  gtk_container_add (GTK_CONTAINER (button14), eventbox69);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (eventbox69), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image19 = gtk_image_new_from_stock ("gtk-properties", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox14), image19, FALSE, FALSE, 0);

  eventbox99 = gtk_event_box_new ();
  gtk_widget_show (eventbox99);
  gtk_box_pack_start (GTK_BOX (hbox14), eventbox99, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("\360\235\220\214\360\235\220\216\360\235\220\203\360\235\220\210\360\235\220\205\360\235\220\210\360\235\220\204\360\235\220\221"));
  gtk_widget_show (label26);
  gtk_container_add (GTK_CONTAINER (eventbox99), label26);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed4), button11, 424, 520);
  gtk_widget_set_size_request (button11, 92, 25);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button11), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  eventbox51 = gtk_event_box_new ();
  gtk_widget_show (eventbox51);
  gtk_box_pack_start (GTK_BOX (hbox11), eventbox51, FALSE, FALSE, 0);

  image15 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_container_add (GTK_CONTAINER (eventbox51), image15);

  label22 = gtk_label_new_with_mnemonic (_("\360\235\221\271\360\235\221\254\360\235\221\273\360\235\221\266\360\235\221\274\360\235\221\271"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox11), label22, FALSE, FALSE, 0);

  label56 = gtk_label_new ("");
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed4), label56, 368, 192);
  gtk_widget_set_size_request (label56, 160, 24);

  label57 = gtk_label_new ("");
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed4), label57, 368, 248);
  gtk_widget_set_size_request (label57, 168, 24);

  label58 = gtk_label_new ("");
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed4), label58, 368, 296);
  gtk_widget_set_size_request (label58, 224, 32);

  label59 = gtk_label_new ("");
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed4), label59, 184, 376);
  gtk_widget_set_size_request (label59, 65, 25);

  label60 = gtk_label_new ("");
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed4), label60, 256, 376);
  gtk_widget_set_size_request (label60, 97, 32);

  label61 = gtk_label_new ("");
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed4), label61, 360, 376);
  gtk_widget_set_size_request (label61, 96, 24);

  label55 = gtk_label_new ("");
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed4), label55, 368, 136);
  gtk_widget_set_size_request (label55, 168, 32);

  label53 = gtk_label_new ("");
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed4), label53, 376, 96);
  gtk_widget_set_size_request (label53, 128, 32);

  verifier = gtk_button_new ();
  gtk_widget_show (verifier);
  gtk_fixed_put (GTK_FIXED (fixed4), verifier, 416, 64);
  gtk_widget_set_size_request (verifier, 104, 32);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (verifier), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image26 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox20), image26, FALSE, FALSE, 0);

  label54 = gtk_label_new_with_mnemonic (_("verifier"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox20), label54, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_button14_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);
  g_signal_connect ((gpointer) verifier, "clicked",
                    G_CALLBACK (on_verifier_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Step4, Step4, "Step4");
  GLADE_HOOKUP_OBJECT (Step4, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Step4, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (Step4, entry_nom, "entry_nom");
  GLADE_HOOKUP_OBJECT (Step4, entryprenom, "entryprenom");
  GLADE_HOOKUP_OBJECT (Step4, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (Step4, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (Step4, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (Step4, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (Step4, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (Step4, eventbox86, "eventbox86");
  GLADE_HOOKUP_OBJECT (Step4, label20, "label20");
  GLADE_HOOKUP_OBJECT (Step4, eventbox89, "eventbox89");
  GLADE_HOOKUP_OBJECT (Step4, label35, "label35");
  GLADE_HOOKUP_OBJECT (Step4, eventbox90, "eventbox90");
  GLADE_HOOKUP_OBJECT (Step4, label27, "label27");
  GLADE_HOOKUP_OBJECT (Step4, eventbox91, "eventbox91");
  GLADE_HOOKUP_OBJECT (Step4, label28, "label28");
  GLADE_HOOKUP_OBJECT (Step4, eventbox93, "eventbox93");
  GLADE_HOOKUP_OBJECT (Step4, label30, "label30");
  GLADE_HOOKUP_OBJECT (Step4, eventbox94, "eventbox94");
  GLADE_HOOKUP_OBJECT (Step4, label29, "label29");
  GLADE_HOOKUP_OBJECT (Step4, eventbox95, "eventbox95");
  GLADE_HOOKUP_OBJECT (Step4, label31, "label31");
  GLADE_HOOKUP_OBJECT (Step4, entry14, "entry14");
  GLADE_HOOKUP_OBJECT (Step4, label49, "label49");
  GLADE_HOOKUP_OBJECT (Step4, button14, "button14");
  GLADE_HOOKUP_OBJECT (Step4, eventbox69, "eventbox69");
  GLADE_HOOKUP_OBJECT (Step4, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Step4, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Step4, image19, "image19");
  GLADE_HOOKUP_OBJECT (Step4, eventbox99, "eventbox99");
  GLADE_HOOKUP_OBJECT (Step4, label26, "label26");
  GLADE_HOOKUP_OBJECT (Step4, button11, "button11");
  GLADE_HOOKUP_OBJECT (Step4, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Step4, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Step4, eventbox51, "eventbox51");
  GLADE_HOOKUP_OBJECT (Step4, image15, "image15");
  GLADE_HOOKUP_OBJECT (Step4, label22, "label22");
  GLADE_HOOKUP_OBJECT (Step4, label56, "label56");
  GLADE_HOOKUP_OBJECT (Step4, label57, "label57");
  GLADE_HOOKUP_OBJECT (Step4, label58, "label58");
  GLADE_HOOKUP_OBJECT (Step4, label59, "label59");
  GLADE_HOOKUP_OBJECT (Step4, label60, "label60");
  GLADE_HOOKUP_OBJECT (Step4, label61, "label61");
  GLADE_HOOKUP_OBJECT (Step4, label55, "label55");
  GLADE_HOOKUP_OBJECT (Step4, label53, "label53");
  GLADE_HOOKUP_OBJECT (Step4, verifier, "verifier");
  GLADE_HOOKUP_OBJECT (Step4, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (Step4, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (Step4, image26, "image26");
  GLADE_HOOKUP_OBJECT (Step4, label54, "label54");

  return Step4;
}

GtkWidget*
create_Step5 (void)
{
  GtkWidget *Step5;
  GtkWidget *fixed5;
  GtkWidget *entry9;
  GtkWidget *eventbox101;
  GtkWidget *label23;
  GtkWidget *eventbox103;
  GtkWidget *button12;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image17;
  GtkWidget *eventbox102;
  GtkWidget *label24;
  GtkWidget *eventbox105;
  GtkWidget *button13;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image18;
  GtkWidget *eventbox104;
  GtkWidget *label25;
  GtkWidget *label45;
  GtkWidget *eventbox108;
  GtkWidget *button19;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image24;
  GtkWidget *eventbox109;
  GtkWidget *label48;
  GtkWidget *eventbox110;
  GtkWidget *button18;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image23;
  GtkWidget *eventbox107;
  GtkWidget *label47;
  GtkWidget *image16;

  Step5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Step5), _("Step.5"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Step5), fixed5);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed5), entry9, 128, 128);
  gtk_widget_set_size_request (entry9, 329, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  eventbox101 = gtk_event_box_new ();
  gtk_widget_show (eventbox101);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox101, 56, 96);
  gtk_widget_set_size_request (eventbox101, 443, 17);

  label23 = gtk_label_new (_("\360\235\231\274\360\235\232\216\360\235\232\233\360\235\232\214\360\235\232\222 \360\235\232\215'\360\235\232\216\360\235\232\227\360\235\232\235\360\235\232\233\360\235\232\216\360\235\232\233 \360\235\232\225'\360\235\232\222\360\235\232\215\360\235\232\216\360\235\232\227\360\235\232\235\360\235\232\222\360\235\232\217\360\235\232\222\360\235\232\212\360\235\232\227\360\235\232\235 \360\235\232\215\360\235\232\216 \360\235\232\237\360\235\232\230\360\235\232\235\360\235\232\233\360\235\232\216 \360\235\232\214\360\235\232\225\360\235\232\222\360\235\232\216\360\235\232\227\360\235\232\235 ! "));
  gtk_widget_show (label23);
  gtk_container_add (GTK_CONTAINER (eventbox101), label23);
  gtk_widget_set_size_request (label23, 443, 17);

  eventbox103 = gtk_event_box_new ();
  gtk_widget_show (eventbox103);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox103, 233, 168);
  gtk_widget_set_size_request (eventbox103, 223, 27);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_container_add (GTK_CONTAINER (eventbox103), button12);
  gtk_widget_set_size_request (button12, 223, 27);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button12), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image17 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox12), image17, FALSE, FALSE, 0);

  eventbox102 = gtk_event_box_new ();
  gtk_widget_show (eventbox102);
  gtk_box_pack_start (GTK_BOX (hbox12), eventbox102, FALSE, FALSE, 1);

  label24 = gtk_label_new_with_mnemonic (_("\360\235\220\222\360\235\220\224\360\235\220\217\360\235\220\217\360\235\220\221\360\235\220\210\360\235\220\214\360\235\220\204\360\235\220\221 \360\235\220\202\360\235\220\204 \360\235\220\202\360\235\220\216\360\235\220\214\360\235\220\217\360\235\220\223\360\235\220\204."));
  gtk_widget_show (label24);
  gtk_container_add (GTK_CONTAINER (eventbox102), label24);

  eventbox105 = gtk_event_box_new ();
  gtk_widget_show (eventbox105);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox105, 370, 429);
  gtk_widget_set_size_request (eventbox105, 91, 25);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_container_add (GTK_CONTAINER (eventbox105), button13);
  gtk_widget_set_size_request (button13, 91, 25);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button13), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image18 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox13), image18, FALSE, FALSE, 0);

  eventbox104 = gtk_event_box_new ();
  gtk_widget_show (eventbox104);
  gtk_box_pack_start (GTK_BOX (hbox13), eventbox104, FALSE, FALSE, 1);

  label25 = gtk_label_new_with_mnemonic (_("\360\235\221\271\360\235\221\254\360\235\221\273\360\235\221\266\360\235\221\274\360\235\221\271"));
  gtk_widget_show (label25);
  gtk_container_add (GTK_CONTAINER (eventbox104), label25);

  label45 = gtk_label_new ("");
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed5), label45, 208, 320);
  gtk_widget_set_size_request (label45, 296, 40);

  eventbox108 = gtk_event_box_new ();
  gtk_widget_show (eventbox108);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox108, 255, 376);
  gtk_widget_set_size_request (eventbox108, 83, 29);

  button19 = gtk_button_new ();
  gtk_widget_show (button19);
  gtk_container_add (GTK_CONTAINER (eventbox108), button19);
  gtk_widget_set_size_request (button19, 83, 29);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button19), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image24 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox19), image24, FALSE, FALSE, 0);

  eventbox109 = gtk_event_box_new ();
  gtk_widget_show (eventbox109);
  gtk_box_pack_start (GTK_BOX (hbox19), eventbox109, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("\360\235\220\216\360\235\220\224\360\235\220\210"));
  gtk_widget_show (label48);
  gtk_container_add (GTK_CONTAINER (eventbox109), label48);

  eventbox110 = gtk_event_box_new ();
  gtk_widget_show (eventbox110);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox110, 360, 376);
  gtk_widget_set_size_request (eventbox110, 83, 29);

  button18 = gtk_button_new ();
  gtk_widget_show (button18);
  gtk_container_add (GTK_CONTAINER (eventbox110), button18);
  gtk_widget_set_size_request (button18, 83, 29);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button18), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image23 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox18), image23, FALSE, FALSE, 0);

  eventbox107 = gtk_event_box_new ();
  gtk_widget_show (eventbox107);
  gtk_box_pack_start (GTK_BOX (hbox18), eventbox107, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_(" \360\235\220\215\360\235\220\216\360\235\220\215 "));
  gtk_widget_show (label47);
  gtk_container_add (GTK_CONTAINER (eventbox107), label47);

  image16 = create_pixmap (Step5, "124965098_749125422677961_5489649082936555166_n.png");
  gtk_widget_show (image16);
  gtk_fixed_put (GTK_FIXED (fixed5), image16, 0, 0);
  gtk_widget_set_size_request (image16, 544, 480);

  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_button12_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_button13_clicked),
                    NULL);
  g_signal_connect ((gpointer) button19, "clicked",
                    G_CALLBACK (on_button19_clicked),
                    NULL);
  g_signal_connect ((gpointer) button18, "clicked",
                    G_CALLBACK (on_button18_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Step5, Step5, "Step5");
  GLADE_HOOKUP_OBJECT (Step5, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Step5, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (Step5, eventbox101, "eventbox101");
  GLADE_HOOKUP_OBJECT (Step5, label23, "label23");
  GLADE_HOOKUP_OBJECT (Step5, eventbox103, "eventbox103");
  GLADE_HOOKUP_OBJECT (Step5, button12, "button12");
  GLADE_HOOKUP_OBJECT (Step5, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Step5, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Step5, image17, "image17");
  GLADE_HOOKUP_OBJECT (Step5, eventbox102, "eventbox102");
  GLADE_HOOKUP_OBJECT (Step5, label24, "label24");
  GLADE_HOOKUP_OBJECT (Step5, eventbox105, "eventbox105");
  GLADE_HOOKUP_OBJECT (Step5, button13, "button13");
  GLADE_HOOKUP_OBJECT (Step5, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Step5, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Step5, image18, "image18");
  GLADE_HOOKUP_OBJECT (Step5, eventbox104, "eventbox104");
  GLADE_HOOKUP_OBJECT (Step5, label25, "label25");
  GLADE_HOOKUP_OBJECT (Step5, label45, "label45");
  GLADE_HOOKUP_OBJECT (Step5, eventbox108, "eventbox108");
  GLADE_HOOKUP_OBJECT (Step5, button19, "button19");
  GLADE_HOOKUP_OBJECT (Step5, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (Step5, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (Step5, image24, "image24");
  GLADE_HOOKUP_OBJECT (Step5, eventbox109, "eventbox109");
  GLADE_HOOKUP_OBJECT (Step5, label48, "label48");
  GLADE_HOOKUP_OBJECT (Step5, eventbox110, "eventbox110");
  GLADE_HOOKUP_OBJECT (Step5, button18, "button18");
  GLADE_HOOKUP_OBJECT (Step5, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (Step5, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (Step5, image23, "image23");
  GLADE_HOOKUP_OBJECT (Step5, eventbox107, "eventbox107");
  GLADE_HOOKUP_OBJECT (Step5, label47, "label47");
  GLADE_HOOKUP_OBJECT (Step5, image16, "image16");

  return Step5;
}

GtkWidget*
create_Step6 (void)
{
  GtkWidget *Step6;
  GtkWidget *fixed6;
  GtkWidget *eventbox111;
  GtkWidget *label51;
  GtkWidget *image25;
  GtkWidget *button20;

  Step6 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Step6), _("Step6"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (Step6), fixed6);

  eventbox111 = gtk_event_box_new ();
  gtk_widget_show (eventbox111);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox111, 160, 192);
  gtk_widget_set_size_request (eventbox111, 152, 24);

  label51 = gtk_label_new (_("\360\235\220\201\360\235\220\242\360\235\220\236\360\235\220\247 \360\235\220\254\360\235\220\256\360\235\220\251\360\235\220\251\360\235\220\253\360\235\220\242\360\235\220\246\360\235\220\236\314\201!"));
  gtk_widget_show (label51);
  gtk_container_add (GTK_CONTAINER (eventbox111), label51);
  gtk_widget_set_size_request (label51, 152, 24);

  image25 = create_pixmap (Step6, "businessman-say-okey_1012-177.jpeg");
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed6), image25, 0, 0);
  gtk_widget_set_size_request (image25, 448, 480);

  button20 = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (button20);
  gtk_fixed_put (GTK_FIXED (fixed6), button20, 200, 224);
  gtk_widget_set_size_request (button20, 80, 24);

  g_signal_connect ((gpointer) button20, "clicked",
                    G_CALLBACK (on_button20_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Step6, Step6, "Step6");
  GLADE_HOOKUP_OBJECT (Step6, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Step6, eventbox111, "eventbox111");
  GLADE_HOOKUP_OBJECT (Step6, label51, "label51");
  GLADE_HOOKUP_OBJECT (Step6, image25, "image25");
  GLADE_HOOKUP_OBJECT (Step6, button20, "button20");

  return Step6;
}

