/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Step1;
  GtkWidget *Step2;
  GtkWidget *Step3;
  GtkWidget *Step4;
  GtkWidget *Step5;
  GtkWidget *Step6;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Step1 = create_Step1 ();
  gtk_widget_show (Step1);
  /*Step2 = create_Step2 ();
  gtk_widget_show (Step2);
  Step3 = create_Step3 ();
  gtk_widget_show (Step3);
  Step4 = create_Step4 ();
  gtk_widget_show (Step4);
  Step5 = create_Step5 ();
  gtk_widget_show (Step5);
  Step6 = create_Step6 ();
  gtk_widget_show (Step6);*/

  gtk_main ();
  return 0;
}

